export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  "United States": [
    "New York",
    "Los Angeles",
    "Chicago",
    "Miami",
    "San Francisco",
    "Austin",
    "Seattle",
    "Boston",
    "Denver",
    "Las Vegas",
    "Orlando",
    "San Diego",
  ],
  Canada: ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa", "Quebec City", "Edmonton"],
  Israel: [
    "Tel Aviv",
    "Jerusalem",
    "Haifa",
    "Eilat",
    "Be'er Sheva",
    "Netanya",
    "Herzliya",
    "Ashdod",
    "Ra'anana",
    "Rishon LeZion",
  ],
  "United Kingdom": ["London", "Manchester", "Edinburgh", "Birmingham", "Liverpool", "Glasgow", "Bristol"],
  Ireland: ["Dublin", "Cork", "Galway", "Limerick"],
  France: ["Paris", "Nice", "Lyon", "Marseille", "Bordeaux", "Cannes", "Toulouse"],
  Germany: ["Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne", "Stuttgart"],
  Spain: ["Barcelona", "Madrid", "Valencia", "Seville", "Malaga", "Palma de Mallorca", "Ibiza"],
  Portugal: ["Lisbon", "Porto", "Faro", "Funchal"],
  Italy: ["Rome", "Milan", "Florence", "Venice", "Naples", "Bologna"],
  Netherlands: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht"],
  Belgium: ["Brussels", "Antwerp", "Ghent", "Bruges"],
  Switzerland: ["Zurich", "Geneva", "Basel", "Bern", "Lucerne"],
  Austria: ["Vienna", "Salzburg", "Innsbruck"],
  Sweden: ["Stockholm", "Gothenburg", "Malmo"],
  Norway: ["Oslo", "Bergen", "Trondheim"],
  Denmark: ["Copenhagen", "Aarhus", "Odense"],
  Finland: ["Helsinki", "Tampere", "Turku"],
  Poland: ["Warsaw", "Krakow", "Gdansk", "Wroclaw"],
  Czechia: ["Prague", "Brno"],
  Greece: ["Athens", "Thessaloniki", "Santorini", "Mykonos", "Crete"],
  Turkey: ["Istanbul", "Antalya", "Izmir", "Ankara", "Bodrum"],
  Cyprus: ["Nicosia", "Limassol", "Larnaca", "Paphos", "Ayia Napa"],
  Romania: ["Bucharest", "Cluj-Napoca", "Timisoara"],
  Hungary: ["Budapest", "Debrecen"],
  Ukraine: ["Kyiv", "Lviv", "Odesa"],
  Russia: ["Moscow", "Saint Petersburg"],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina"],
  Egypt: ["Cairo", "Alexandria", "Hurghada", "Sharm El Sheikh"],
  Jordan: ["Amman", "Aqaba", "Petra"],
  "South Africa": ["Cape Town", "Johannesburg", "Durban", "Pretoria"],
  India: ["Mumbai", "Delhi", "Bengaluru", "Goa", "Jaipur", "Chennai"],
  China: ["Shanghai", "Beijing", "Shenzhen", "Guangzhou", "Hong Kong"],
  Japan: ["Tokyo", "Osaka", "Kyoto", "Yokohama"],
  "South Korea": ["Seoul", "Busan", "Incheon"],
  Singapore: ["Singapore"],
  Thailand: ["Bangkok", "Phuket", "Chiang Mai", "Pattaya"],
  Australia: ["Sydney", "Melbourne", "Brisbane", "Perth", "Gold Coast"],
  "New Zealand": ["Auckland", "Wellington", "Queenstown", "Christchurch"],
  Mexico: ["Mexico City", "Cancun", "Guadalajara", "Playa del Carmen", "Tulum"],
  Brazil: ["Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador"],
  Argentina: ["Buenos Aires", "Cordoba", "Mendoza", "Bariloche"],
  Colombia: ["Bogota", "Medellin", "Cartagena"],
  Chile: ["Santiago", "Valparaiso"],
};
